// Package sections keeps the user's Overview and project-page sections:
// declarative widgets, each one JSON file in <DataDir>/sections/. A section
// names one read-only Lucidbench GET route from an allowlist, the rows and
// fields to show from its answer, and a view (stat, list, table, bars or
// markdown). It holds no code, no URL and no markup: the web UI's
// SectionRenderer reads it and fetches the route itself.
//
// A section can be written by hand, added from a built-in template, or
// described in words and generated by the user's own CLI with no tools (see
// generate.go). Every way in goes through Validate.
package sections

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// Views a section can use.
var Views = []string{"stat", "list", "table", "bars", "markdown"}

// Placements: on Overview, or on every project's page (where the value
// "{project}" in a filter stands for that project's id).
const (
	PlaceOverview = "overview"
	PlaceProject  = "project"
)

// ProjectToken stands for the project's id in a filter value of a project
// section.
const ProjectToken = "{project}"

// Formats a field can be shown in.
var Formats = []string{"text", "number", "usd", "percent", "date", "relative", "link", "badge"}

// Aggregates a stat can compute over the rows.
var Aggregates = []string{"count", "sum", "avg", "min", "max"}

// Filter operators.
var Ops = []string{"eq", "ne", "in", "nin", "contains", "exists", "missing", "gt", "lt", "within_days", "since_days"}

// Limits.
const (
	MaxBytes       = 16 << 10
	MaxSections    = 50
	MaxTitle       = 80
	MaxDescription = 240
	MaxFields      = 8
	MaxFilters     = 6
	MaxParams      = 4
	MaxString      = 200
	MaxLimit       = 50
	MinRefresh     = 15
	MaxRefresh     = 3600
	DefaultRefresh = 60
	DefaultLimit   = 10
)

// Source is the route a section reads and its parameters. Params go into the
// route's {placeholders} or its query string; each API says which it takes.
type Source struct {
	API    string `json:"api"`
	Params Params `json:"params,omitempty"`
}

// Params are a route's parameters. They are strings, but a number or a
// true/false is read as its text: models write {"days": 7} as often as
// {"days": "7"}, and both mean the same query.
type Params map[string]string

// UnmarshalJSON reads string, number and boolean values.
func (p *Params) UnmarshalJSON(b []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(b, &raw); err != nil {
		return errors.New("source.params must be a mapping of names to values")
	}
	out := Params{}
	for k, v := range raw {
		var s string
		var n json.Number
		var t bool
		switch {
		case json.Unmarshal(v, &s) == nil:
			out[k] = s
		case json.Unmarshal(v, &n) == nil:
			out[k] = n.String()
		case json.Unmarshal(v, &t) == nil:
			out[k] = strconv.FormatBool(t)
		default:
			return fmt.Errorf("source.params.%s must be a string or a number", trimTo(k, 30))
		}
	}
	*p = out
	return nil
}

// Field is one value shown: a path into a row (or into the answer, for a
// stat or markdown without rows).
type Field struct {
	Path   string `json:"path"`
	Label  string `json:"label,omitempty"`
	Format string `json:"format,omitempty"`
	// Agg, on a stat's field, computes over the rows: count ignores Path.
	Agg string `json:"agg,omitempty"`
}

// Filter keeps the rows whose field passes Op against Value. Value is a
// string, number or bool, or a list of strings for in and nin.
type Filter struct {
	Field string `json:"field"`
	Op    string `json:"op"`
	Value any    `json:"value,omitempty"`
}

// Sort orders the rows by a field.
type Sort struct {
	Field string `json:"field"`
	Desc  bool   `json:"desc,omitempty"`
}

// Section is one widget.
type Section struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	Placement   string `json:"placement,omitempty"`
	Source      Source `json:"source"`
	View        string `json:"view"`
	// Rows is the path to the list to show ("" for an answer that is a
	// list). A "*" segment takes every value of a mapping, so
	// "projects.*" flattens {"projects": {"a": [..], "b": [..]}}; each such
	// row gets "_key", the mapping key it came from.
	Rows     string   `json:"rows,omitempty"`
	Filter   []Filter `json:"filter,omitempty"`
	Sort     *Sort    `json:"sort,omitempty"`
	Limit    int      `json:"limit,omitempty"`
	Fields   []Field  `json:"fields"`
	RefreshS int      `json:"refresh_s,omitempty"`
}

// ParamRule is what one parameter of an API accepts.
type ParamRule struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"` // id | int | text
	Min      int    `json:"min,omitempty"`
	Max      int    `json:"max,omitempty"`
	Required bool   `json:"required,omitempty"`
	Doc      string `json:"doc"`
}

// API is one allowlisted route.
type API struct {
	Route  string      `json:"route"`
	Doc    string      `json:"doc"`
	Params []ParamRule `json:"params"`
	// Rows suggests the list paths in the answer.
	Rows []string `json:"rows"`
}

// APIs is the allowlist: read-only GET routes whose answers hold nothing
// secret. Nothing else can be a section's source. The system prompt in
// prompts/section.md describes each one's answer; a test keeps the two in
// step.
var APIs = []API{
	{Route: "/api/work/sessions", Doc: "Work sessions (agent runs), newest first", Params: []ParamRule{}, Rows: []string{""}},
	{Route: "/api/council/sessions", Doc: "Council sessions (braindumps and their briefs), newest first", Params: []ParamRule{}, Rows: []string{""}},
	{Route: "/api/ideas", Doc: "Ideas: each braindump followed through brief, card, work and PR", Params: []ParamRule{}, Rows: []string{""}},
	{Route: "/api/boards", Doc: "Board summaries", Params: []ParamRule{}, Rows: []string{""}},
	{Route: "/api/boards/{board}", Doc: "One board with its cards", Params: []ParamRule{
		{Name: "board", Kind: "id", Required: true, Doc: "board id, for example work"},
	}, Rows: []string{"cards"}},
	{Route: "/api/projects", Doc: "The projects in projects.yaml", Params: []ParamRule{}, Rows: []string{"projects"}},
	{Route: "/api/usage/summary", Doc: "Token use and cost per provider, and what Lucidbench's own runs spent", Params: []ParamRule{
		{Name: "days", Kind: "int", Min: 1, Max: 90, Doc: "days to cover, 1 to 90 (default 30)"},
	}, Rows: []string{"providers", "lucidbench.providers", "lucidbench.sources", "lucidbench.daily"}},
	{Route: "/api/ci/runs", Doc: "Recent GitHub Actions runs of the configured repositories", Params: []ParamRule{}, Rows: []string{"runs"}},
	{Route: "/api/ci/runners", Doc: "Self-hosted runners and runner containers", Params: []ParamRule{}, Rows: []string{"runners", "containers"}},
	{Route: "/api/cloud/deploys", Doc: "Each project's deploys matched to the cloud inventory", Params: []ParamRule{}, Rows: []string{"projects.*"}},
	{Route: "/api/accounts", Doc: "Detected provider account profiles (never secrets)", Params: []ParamRule{}, Rows: []string{""}},
	{Route: "/api/mcp", Doc: "MCP servers per AI client", Params: []ParamRule{}, Rows: []string{"servers"}},
	{Route: "/api/memory/search", Doc: "Full-text search of the Memory vault", Params: []ParamRule{
		{Name: "q", Kind: "text", Required: true, Max: 100, Doc: "the words to find"},
		{Name: "limit", Kind: "int", Min: 1, Max: 50, Doc: "most hits, 1 to 50"},
	}, Rows: []string{""}},
}

// FindAPI returns the allowlisted route, or nil.
func FindAPI(route string) *API {
	for i := range APIs {
		if APIs[i].Route == route {
			return &APIs[i]
		}
	}
	return nil
}

var (
	idRE    = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,47}$`)
	pathRE  = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*(\.([A-Za-z_][A-Za-z0-9_]*|[0-9]{1,3}))*$`)
	rowsRE  = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*|\*)(\.([A-Za-z_][A-Za-z0-9_]*|[0-9]{1,3}|\*))*$`)
	paramID = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,63}$`)
	// unsafe finds what a section never needs: a URL, markup, a script
	// scheme or a path separator that could reach outside a route.
	unsafe = regexp.MustCompile(`(?i)(://|^//|[<>\\` + "`" + `]|\b(javascript|data|vbscript|file):\S)`)
)

// Problem is one reason a section is refused.
type Problem struct {
	Path    string `json:"path"`
	Message string `json:"message"`
}

func (p Problem) String() string {
	if p.Path == "" {
		return p.Message
	}
	return p.Path + ": " + p.Message
}

// ErrInvalid wraps every validation failure.
var ErrInvalid = errors.New("invalid section")

// ValidationError lists every problem found.
type ValidationError struct{ Problems []Problem }

func (e *ValidationError) Error() string {
	var ss []string
	for _, p := range e.Problems {
		ss = append(ss, p.String())
	}
	return "invalid section: " + strings.Join(ss, "; ")
}

func (e *ValidationError) Unwrap() error { return ErrInvalid }

func oneOf(v string, list []string) bool {
	for _, x := range list {
		if x == v {
			return true
		}
	}
	return false
}

// Parse decodes a section strictly: unknown keys are refused.
func Parse(data []byte) (Section, error) {
	var s Section
	if len(data) > MaxBytes {
		return s, &ValidationError{[]Problem{{"", fmt.Sprintf("larger than %d KB", MaxBytes>>10)}}}
	}
	dec := json.NewDecoder(strings.NewReader(string(data)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&s); err != nil {
		return s, &ValidationError{[]Problem{{"", "not a section: " + strings.TrimPrefix(err.Error(), "json: ")}}}
	}
	if dec.More() {
		return s, &ValidationError{[]Problem{{"", "more than one JSON value"}}}
	}
	return s, nil
}

// Normalise fills defaults: overview placement, the refresh and limit, and
// the first view's empty labels stay empty (the renderer uses the path).
func Normalise(s Section) Section {
	s.ID, s.Title, s.Description = strings.TrimSpace(s.ID), strings.TrimSpace(s.Title), strings.TrimSpace(s.Description)
	if s.Placement == "" {
		s.Placement = PlaceOverview
	}
	if s.RefreshS == 0 {
		s.RefreshS = DefaultRefresh
	}
	if s.Limit == 0 && s.View != "stat" && s.View != "markdown" {
		s.Limit = DefaultLimit
	}
	return s
}

// Validate checks a normalised section. It refuses any API outside the
// allowlist, any parameter the API does not take, any string that holds a
// URL, markup or a script, and any path that is not a plain field path.
func Validate(s Section) error {
	var ps []Problem
	bad := func(path, format string, a ...any) { ps = append(ps, Problem{path, fmt.Sprintf(format, a...)}) }
	text := func(path, v string, max int) {
		if len(v) > max {
			bad(path, "longer than %d characters", max)
		}
		if unsafe.MatchString(v) {
			bad(path, "may not hold a URL, markup or a script")
		}
		for _, r := range v {
			if r < 0x20 {
				bad(path, "has a control character")
				break
			}
		}
	}
	if !idRE.MatchString(s.ID) {
		bad("id", "must be 1-48 lowercase letters, digits and dashes")
	}
	if s.Title == "" {
		bad("title", "is empty")
	}
	text("title", s.Title, MaxTitle)
	text("description", s.Description, MaxDescription)
	if !oneOf(s.Placement, []string{PlaceOverview, PlaceProject}) {
		bad("placement", "must be overview or project")
	}
	if !oneOf(s.View, Views) {
		bad("view", "must be one of %s", strings.Join(Views, ", "))
	}
	if s.RefreshS < MinRefresh || s.RefreshS > MaxRefresh {
		bad("refresh_s", "must be between %d and %d seconds", MinRefresh, MaxRefresh)
	}
	if s.Limit < 0 || s.Limit > MaxLimit {
		bad("limit", "must be between 1 and %d", MaxLimit)
	}

	api := FindAPI(s.Source.API)
	if api == nil {
		bad("source.api", "%q is not an allowed route; use one of the listed read-only Lucidbench routes", trimTo(s.Source.API, 60))
	} else {
		if len(s.Source.Params) > MaxParams {
			bad("source.params", "at most %d", MaxParams)
		}
		rules := map[string]ParamRule{}
		for _, r := range api.Params {
			rules[r.Name] = r
			if _, ok := s.Source.Params[r.Name]; r.Required && !ok {
				bad("source.params."+r.Name, "is required by %s", api.Route)
			}
		}
		for k, v := range s.Source.Params {
			r, ok := rules[k]
			if !ok {
				bad("source.params."+trimTo(k, 30), "%s takes no such parameter", api.Route)
				continue
			}
			text("source.params."+k, v, MaxString)
			switch r.Kind {
			case "id":
				if !paramID.MatchString(v) {
					bad("source.params."+k, "must be an id (lowercase letters, digits, dashes)")
				}
			case "int":
				n, err := strconv.Atoi(v)
				if err != nil || n < r.Min || n > r.Max {
					bad("source.params."+k, "must be a whole number from %d to %d", r.Min, r.Max)
				}
			case "text":
				if strings.TrimSpace(v) == "" || len(v) > r.Max {
					bad("source.params."+k, "must be 1 to %d characters", r.Max)
				}
			}
		}
	}

	if s.Rows != "" && !rowsRE.MatchString(s.Rows) {
		bad("rows", "must be a field path such as cards or projects.* ")
	}
	needsRows := s.View == "list" || s.View == "table" || s.View == "bars"
	if len(s.Fields) == 0 {
		bad("fields", "list at least one field")
	}
	if len(s.Fields) > MaxFields {
		bad("fields", "at most %d", MaxFields)
	}
	if s.View == "bars" && len(s.Fields) != 2 {
		bad("fields", "bars take two fields: the label, then the value")
	}
	for i, f := range s.Fields {
		p := fmt.Sprintf("fields.%d", i)
		if f.Agg != "count" && !pathRE.MatchString(f.Path) {
			bad(p+".path", "must be a field path such as title or usage.cost_usd")
		}
		text(p+".label", f.Label, MaxTitle)
		if f.Format != "" && !oneOf(f.Format, Formats) {
			bad(p+".format", "must be one of %s", strings.Join(Formats, ", "))
		}
		if f.Agg != "" {
			if s.View != "stat" || i != 0 {
				bad(p+".agg", "only a stat's first field computes over the rows")
			} else if !oneOf(f.Agg, Aggregates) {
				bad(p+".agg", "must be one of %s", strings.Join(Aggregates, ", "))
			}
		}
	}
	if len(s.Filter) > MaxFilters {
		bad("filter", "at most %d", MaxFilters)
	}
	for i, f := range s.Filter {
		p := fmt.Sprintf("filter.%d", i)
		if !pathRE.MatchString(f.Field) {
			bad(p+".field", "must be a field path")
		}
		if !oneOf(f.Op, Ops) {
			bad(p+".op", "must be one of %s", strings.Join(Ops, ", "))
			continue
		}
		checkValue(p+".value", f, s.Placement, bad, text)
	}
	if s.Sort != nil && !pathRE.MatchString(s.Sort.Field) {
		bad("sort.field", "must be a field path")
	}
	if (len(s.Filter) > 0 || s.Sort != nil) && !needsRows && !(s.View == "stat" && len(s.Fields) > 0 && s.Fields[0].Agg != "") {
		bad("filter", "filters and sorting need rows: use list, table, bars or a stat with agg")
	}
	if len(ps) > 0 {
		return &ValidationError{ps}
	}
	return nil
}

func checkValue(p string, f Filter, placement string, bad func(string, string, ...any), text func(string, string, int)) {
	str := func(v string) {
		text(p, v, MaxString)
		if strings.Contains(v, "{") && v != ProjectToken {
			bad(p, "the only placeholder is %s", ProjectToken)
		}
		if v == ProjectToken && placement != PlaceProject {
			bad(p, "%s works only in a project section", ProjectToken)
		}
	}
	switch f.Op {
	case "exists", "missing":
		if f.Value != nil {
			bad(p, "%s takes no value", f.Op)
		}
	case "in", "nin":
		list, ok := f.Value.([]any)
		if !ok || len(list) == 0 || len(list) > 20 {
			bad(p, "%s takes a list of 1 to 20 strings", f.Op)
			return
		}
		for _, it := range list {
			s, ok := it.(string)
			if !ok {
				bad(p, "%s takes strings", f.Op)
				return
			}
			str(s)
		}
	case "gt", "lt", "within_days", "since_days":
		n, ok := f.Value.(float64)
		if !ok {
			bad(p, "%s takes a number", f.Op)
			return
		}
		if (f.Op == "within_days" || f.Op == "since_days") && (n < 0 || n > 3650) {
			bad(p, "days must be from 0 to 3650")
		}
	default: // eq, ne, contains
		switch v := f.Value.(type) {
		case string:
			str(v)
		case float64, bool:
		default:
			bad(p, "%s takes a string, number or true/false", f.Op)
		}
	}
}

func trimTo(s string, n int) string {
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

// Check parses, normalises and validates raw JSON in one step.
func Check(data []byte) (Section, error) {
	s, err := Parse(data)
	if err != nil {
		return s, err
	}
	s = Normalise(s)
	return s, Validate(s)
}
